spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jackson:
    serialization:
      indent-output: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /


logging:
  level:
    com.whyalwaysmea.account.mapper: TRACE




