spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jackson:
    serialization:
      indent-output: true
  redis:
    host: localhost
    port: 6379


logging:
  level:
    com.whyalwaysmea.account.mapper: TRACE


